### PR TITLE
SDSS-1268: Removed the white option for row backgrounds

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW

# Summary
- Removed the white background option from layouts.

# Review By (Date)
- as time allows

# Criticality
- normal

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to to a new page.
3. Create a row. 
4. Verify you can no longer add a white background to a row. 

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Review by joegl — CHANGES_REQUESTED** [review]
We can't just remove an option from a select field. If the option is used somewhere we need to change the value to an existing one. This will require a database update hook.

**Comment by jenbreese** [comment]
@joegl Should I go ahead and close this and the row background colors be part of the new work from yesterday?

**Comment by joegl** [comment]
@jenbreese I added an update hook to migrate any layout paragraph with a white background color to "none".

**Comment by joegl** [comment]
@jenbreese Here are some steps to test the database update on local or gitpod:

1. In the `docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/src/Plugin/Layout/SdssLayoutParagraphBase.php` file, re-add the "white" bg_color that was removed (only for testing)
2. Create a new page with a layout paragraph using the "white" background color and save it
3. Reset the schema version for `sdss_profile` with drush (to re-trigger database update): `drush "\Drupal::service('update.update_hook_registry')->setInstalledVersion('sdss_profile', 10006);"`
4. Run database update: `drush updatedb -y`
5. Edit the page created and confirm the layout paragraph with the "white" background color is now set to "none"

**Comment by jenbreese** [comment]
Hi @joegl, I tried it and it did reset the choice to `none`. So I think we are good to go for after the code freeze.

**Comment by joegl** [comment]
> Hi @joegl, I tried it and it did reset the choice to `none`. So I think we are good to go for after the code freeze.

Awesome, thanks Jen! We'll get this merged after the 6/5 deploy/code freeze.

**Review by joegl — APPROVED** [review]
LGTM (and Jen 😄 ). Thanks Jen!

**Pull request merged**
