### PR TITLE
SDSS-1235: local footer config update

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW

# Summary
- Removed Content Block 4 from the Local Footer config file.

# Review By (Date)
- When time allows

# Criticality
Normal

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Import configs
3. Navigate to Local Footer Config
4. Verify there isn't a Fourth Content block

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
[- SDSS-1235](https://stanfordits.atlassian.net/browse/SDSS-1235)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Review by jdwjdwjdw — COMMENTED** [review]
Looks good, but I think your changes are breaking the Local Footer Codeception tests

**Comment by joegl** [comment]
> Looks good, but I think your changes are breaking the Local Footer Codeception tests

@jenbreese Jacob is right. You'll want to remove these two lines from the test file:

- https://github.com/SU-SWS/ace-sdssgryphon/blob/17d66bfbe34ccd8b1b6d60c80acf6d3f9e191871/docroot/profiles/sdss/sdss_profile/tests/codeception/acceptance/LocalFooter/LocalFooterCest.php#L104C21-L104C53
- https://github.com/SU-SWS/ace-sdssgryphon/blob/17d66bfbe34ccd8b1b6d60c80acf6d3f9e191871/docroot/profiles/sdss/sdss_profile/tests/codeception/acceptance/LocalFooter/LocalFooterCest.php#L111

**Comment by jenbreese** [comment]
@jdwjdwjdw I fixed the code errors and it is ready for you to look at.

**Review by jdwjdwjdw — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
